default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: swapn
  password: postgres
  host: localhost

development:
  <<: *default
  database: todo_app_development

test:
  <<: *default
  database: todo_app_test

production:
  <<: *default
  database: todo_app_production
  username: swapn
  password: <%= ENV['TODO_APP_DATABASE_PASSWORD'] %>

